spring:
  flyway:
    locations: classpath:db/migration,db/dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/job_offer_dev?characterEncoding=utf8
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
logging:
  level: DEBUG
