version: "3"
services:
  nuxt:
    build:
      context: ..
      dockerfile: ./docker/nuxt/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ../front/job-offer-front:/usr/src/app
    env_file:
      - './nuxt/env/.env.development'
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./db/init-sql:/docker-entrypoint-initdb.d
      - ./db/mysql/volumes:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - "./redis:/data"
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
      - 1025:1025