BEGIN;
INSERT INTO jobs(`name`) VALUES ('バックエンドエンジニア');
INSERT INTO jobs(`name`) VALUE ('フロントエンドエンジニア');
INSERT INTO jobs(`name`) VALUE ('SRE');
INSERT INTO jobs(`name`) VALUE ('iOSエンジニア');
INSERT INTO jobs(`name`) VALUE ('Androidエンジニア');
INSERT INTO jobs(`name`) VALUE ('インフラエンジニア');
INSERT INTO jobs(`name`) VALUE ('モバイルエンジニア');
INSERT INTO jobs(`name`) VALUE ('フルスタックエンジニア');
INSERT INTO jobs(`name`) VALUE ('機械学習エンジニア');
INSERT INTO jobs(`name`) VALUE ('エンジニアリングマネージャー');
INSERT INTO jobs(`name`) VALUE ('スクラムマスター');
INSERT INTO jobs(`name`) VALUE ('プロダクトオーナー');
INSERT INTO jobs(`name`) VALUE ('QAエンジニア');
INSERT INTO jobs(`name`) VALUE ('プロジェクトマネージャー');
INSERT INTO jobs(`name`) VALUE ('Webデザイナー');
INSERT INTO jobs(`name`) VALUE ('データサイエンティスト');
INSERT INTO jobs(`name`) VALUE ('クラウドエンジニア');
INSERT INTO jobs(`name`) VALUE ('CTO');
INSERT INTO jobs(`name`) VALUE ('テックリード');
INSERT INTO jobs(`name`) VALUE ('システムアーキテクト');
COMMIT;